version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: greenstamp-postgres
    environment:
      POSTGRES_DB: greenstamp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - greenstamp-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: greenstamp-api
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_NAME=greenstamp
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - JWT_EXPIRES_IN=7d
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - greenstamp-network
    command: npm run start:dev

volumes:
  postgres_data:

networks:
  greenstamp-network:
    driver: bridge